### ISSUE TITLE
Won't render

### ISSUE THREAD

**Issue by ChipNowacek** [VisualDataWeb/WebVOWL#87]
Ran `grunt webserver`. Even though the validator says it's okay, I can't get this ontology to render. What am I doing wrong?

```
Prefix: : <http://snwb.twostewards.com/test#>
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>

Ontology: <http://snwb.twostewards.com/test>
    
ObjectProperty: isRelatedTo
    Domain: 
        This
    Range: 
        That

Class: This
    EquivalentTo: 
        isRelatedTo some That

Class: That

```
![screen shot 2017-03-24 at 5 40 13 pm](https://cloud.githubusercontent.com/assets/3668197/24314630/015e587c-10b9-11e7-9e89-61c06af6da84.png)
